backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  
  - name: "common"
    label: "common"
    files:
      - name: 'header'
        label: "Header"
        file: "src/pages/header/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "header"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Numero de telefono", name: "telephone", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {
              label: "Location",
              name: "location",
              required: true,
              widget: "object",
              fields:
                [
                  { label: "Name", name: "name", widget: "string" },
                  { label: "Google Maps Link", name: "mapsLink", widget: "string" },
                  { label: texto, name: body, widget: markdown}
                ],
            }
          - {
              label: "Tratamientos",
              name: "tratement",
              widget: "object",
              fields: [
                {
                    label: "Tratamiento 1",
                    name: "firstTratement",
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {label:  Image, name: image, widget: image}
                      ]
                },
                {
                    label: "Tratamiento 2",
                    name: "secondTratement",
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {label:  Image, name: image, widget: image}
                      ]
                },
                {
                    label: "Tratamiento 3",
                    name: "threeTratement",
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {label:  Image, name: image, widget: image}
                      ]
                },
                {
                    label: "Tratamiento 4",
                    name: "fourTratement",
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {label:  Image, name: image, widget: image}
                      ]
                },
              ]
            }
          - {
              label: "SlideShow",
              name: "slideshow",
              required: true,
              widget: "object",
              fields:
                [
                  {
                    label: "First Picture",
                    name: "firstpicture",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" }
                      ]
                  },
                  {
                    label: "Second Picture",
                    name: "secondpicture",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" }
                      ]
                    
                  },
                  {  
                    label: "Third Picture",
                    name: "thirdpicture",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" }
                      ]
                  }
                  
                ]
            }
          - {
              label: Nuestro equipo, 
              name: ourteam, 
              widget: object,
              fields: [
                { label: Title, name: title, widget: string},
                { label: texto, name: body, widget: markdown},
                { label: "Image", name: "image", widget: "image" },
                { label: "Image Description", name: "imageAlt", widget: "string" }
              ]
            }

      
     