backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  
  - name: "common"
    label: "common"
    files:
      - name: 'header'
        label: "Header"
        file: "src/pages/header/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "header"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Numero de telefono", name: "telephone", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
      
     